import 'dart:convert';
import 'dart:io';

import 'package:flutter/foundation.dart';

import 'feature_tier.dart';

/// Server-validated license with local caching.
///
/// Flow:
///   1. Key sent to InkPal API (`POST /api/license/validate`)
///   2. Server validates via Razorpay / Supabase licenses table, returns signed grant:
///      `{ tier, features[], exp, sig }`
///   3. Grant cached locally until `exp` (default 24h from server)
///   4. Each feature check reads the cached grant
///
/// The HMAC signing secret lives on the server. The client verifies
/// that `sig` is present and non-empty — a missing sig means the
/// response wasn't generated by our server. Full HMAC verification
/// would require embedding the secret client-side (defeats the purpose),
/// so transport security (HTTPS) is the real protection layer.
class InkPalLicense {
  static InkPalLicense? _instance;

  InkPalTier _tier = InkPalTier.free;
  Set<InkPalFeature> _features = InkPalTier.free.features;
  DateTime? _grantExpiry;
  bool _validated = false;
  DateTime? _lastValidation;

  /// Tier observed at the START of this Dart VM session — used to detect
  /// upgrades that landed between sessions. Set on the first successful
  /// `validate()` and never overwritten by later validations in the same
  /// session, so [tierUpgradedSinceSessionStart] stays meaningful.
  InkPalTier? _sessionStartTier;

  /// Most recent tier returned by the server (updated every successful
  /// validate). Compared against [_sessionStartTier] to detect upgrades.
  InkPalTier? _latestTier;

  /// Stable callback that fires once when the latest server-reported tier
  /// is strictly greater than the tier observed at session start. Bridge
  /// owners use this to surface the "your plan was upgraded — restart
  /// the Flutter run / IDE session to load new features" banner.
  void Function(InkPalTier from, InkPalTier to)? onTierUpgrade;
  bool _upgradeFired = false;

  /// Current tier (free until validated).
  /// Current tier — always evaluates grace period so callers using `tier`
  /// directly (not `hasFeature`) still receive the correct downgraded value.
  InkPalTier get tier {
    _evaluateGracePeriod();
    return _tier;
  }

  /// Evaluate post-expiry grace period and downgrade if it has ended.
  /// Safe to call repeatedly — no-ops when not expired.
  void _evaluateGracePeriod() {
    if (_grantExpiry == null || !DateTime.now().isAfter(_grantExpiry!)) return;
    final daysPastExpiry = DateTime.now().difference(_grantExpiry!).inDays;
    if (daysPastExpiry > 7 && _tier != InkPalTier.free) {
      debugPrint('[InkPal License] Grace period ended — downgrading to free tier');
      _tier = InkPalTier.free;
      _features = InkPalTier.free.features;
      _validated = false;
    }
  }

  /// Whether the license has been server-validated.
  bool get isValidated => _validated;

  /// Singleton access.
  static InkPalLicense get instance => _instance ??= InkPalLicense._();

  InkPalLicense._();

  /// Check if a specific feature is unlocked.
  ///
  /// After grant expiry, a 7-day grace period keeps features active
  /// while warning the user. After 7 days, hard downgrade to free tier.
  bool hasFeature(InkPalFeature feature) {
    if (_grantExpiry != null && DateTime.now().isAfter(_grantExpiry!)) {
      final daysPastExpiry = DateTime.now().difference(_grantExpiry!).inDays;
      if (daysPastExpiry <= 7) {
        // Grace period — features still work but warn
        debugPrint('[InkPal License] License expired ${daysPastExpiry}d ago — grace period active (${7 - daysPastExpiry}d remaining)');
        return _features.contains(feature);
      }
      // Past grace period — delegate to _evaluateGracePeriod for consistent downgrade
      _evaluateGracePeriod();
    }
    return _features.contains(feature);
  }

  /// Returns grace period info, or null if not in grace period.
  Map<String, dynamic>? get gracePeriodStatus {
    if (_grantExpiry == null || !DateTime.now().isAfter(_grantExpiry!)) return null;
    final daysPast = DateTime.now().difference(_grantExpiry!).inDays;
    if (daysPast > 7) return null;
    return {
      'active': true,
      'days_remaining': 7 - daysPast,
      'expires_at': _grantExpiry!.add(const Duration(days: 7)).toIso8601String(),
    };
  }

  /// Validate a license key against the InkPal server.
  ///
  /// [apiUrl] — the InkPal API base URL (e.g. Railway deployment).
  /// [licenseKey] — the user's license key.
  ///
  /// Returns true if validation succeeded and features were unlocked.
  Future<bool> validate({
    required String apiUrl,
    required String licenseKey,
  }) async {
    if (_lastValidation != null && DateTime.now().difference(_lastValidation!).inSeconds < 60) {
      debugPrint('[InkPal License] Validation throttled — last validated ${DateTime.now().difference(_lastValidation!).inSeconds}s ago');
      return _validated;
    }
    // Set throttle immediately to prevent concurrent duplicate calls.
    // Reset to null on network error so the user can retry without waiting 60s.
    _lastValidation = DateTime.now();

    final client = HttpClient();
    try {
      final uri = Uri.parse('$apiUrl/api/license/validate');
      client.connectionTimeout = const Duration(seconds: 10);

      final request = await client.postUrl(uri);
      request.headers.set('Content-Type', 'application/json');
      request.write(jsonEncode({
        'key': licenseKey,
        'client': 'inkpal_bridge',
        'version': '1.0.0',
        'platform': defaultTargetPlatform.name,
      }));

      final response = await request.close();
      final body = await response.transform(utf8.decoder).join();

      if (response.statusCode != 200) {
        debugPrint('[InkPal License] Validation failed: ${response.statusCode}');
        // Keep throttle — server explicitly rejected the key.
        return false;
      }

      final data = jsonDecode(body) as Map<String, dynamic>;
      return _applyGrant(data);
    } catch (e) {
      // Network failure — reset throttle so the user can retry immediately.
      _lastValidation = null;
      debugPrint('[InkPal License] Validation error: $e');
      return false;
    } finally {
      client.close(force: true);
    }
  }

  /// Apply a server grant to unlock features.
  ///
  /// Expected shape from POST /api/license/validate:
  ///   `{ tier: "free"|"pro"|"studio", features: [...], exp: <epoch_ms>, sig: "<hmac_hex>" }`
  bool _applyGrant(Map<String, dynamic> grant) {
    // Check for error response
    if (grant.containsKey('error')) {
      debugPrint('[InkPal License] Server error: ${grant['error']}');
      return false;
    }

    final tierName = grant['tier'] as String?;
    final sig = grant['sig'] as String?;
    final expMs = grant['exp'] as int?;
    final featureList = grant['features'] as List<dynamic>?;

    if (tierName == null || sig == null || sig.isEmpty) {
      debugPrint('[InkPal License] Invalid grant: missing tier or sig');
      return false;
    }

    // Basic sig integrity check — must be a 64-char hex string (SHA-256)
    if (sig.length != 64 || !RegExp(r'^[0-9a-f]+$').hasMatch(sig)) {
      debugPrint('[InkPal License] Invalid grant signature format');
      return false;
    }

    // Parse tier
    _tier = InkPalTier.values.firstWhere(
      (t) => t.name == tierName,
      orElse: () => InkPalTier.free,
    );

    // Parse features — server may grant a custom subset
    if (featureList != null && featureList.isNotEmpty) {
      _features = featureList
          .map((f) => InkPalFeature.values.firstWhere(
                (v) => v.name == f,
                orElse: () => InkPalFeature.inspection,
              ))
          .toSet();
    } else {
      _features = _tier.features;
    }

    // Parse expiry
    if (expMs != null) {
      _grantExpiry = DateTime.fromMillisecondsSinceEpoch(expMs);
    } else {
      // Default: 24 hours from now
      _grantExpiry = DateTime.now().add(const Duration(hours: 24));
    }

    _validated = true;
    _latestTier = _tier;
    // First successful validation in this session — pin the baseline tier
    // so future validations can detect upgrades. (We deliberately do NOT
    // pin the tier on subsequent calls — that would mask upgrades.)
    _sessionStartTier ??= _tier;
    _checkAndFireUpgrade();
    debugPrint('[InkPal License] Validated: tier=$tierName, '
        'features=${_features.map((f) => f.name).join(",")}, '
        'expires=$_grantExpiry');
    return true;
  }

  void _checkAndFireUpgrade() {
    if (_upgradeFired || _sessionStartTier == null || _latestTier == null) return;
    final from = _sessionStartTier!;
    final to = _latestTier!;
    if (to.index <= from.index) return; // not an upgrade (downgrades silent)
    _upgradeFired = true;
    debugPrint(
      '[InkPal License] ⚡ Plan upgrade detected: ${from.name} → ${to.name}. '
      'Restart `flutter run` / your IDE session to unlock the new tools.',
    );
    onTierUpgrade?.call(from, to);
  }

  /// True when the server has reported a strictly-higher tier than the one
  /// observed at session start. Bridge command handlers use this to gate
  /// the "session restart needed" banner.
  bool get tierUpgradedSinceSessionStart {
    if (_sessionStartTier == null || _latestTier == null) return false;
    return _latestTier!.index > _sessionStartTier!.index;
  }

  InkPalTier? get sessionStartTier => _sessionStartTier;
  InkPalTier? get latestTier => _latestTier;

  /// Apply a grant directly (for testing without a real server).
  @visibleForTesting
  bool applyGrantForTesting(Map<String, dynamic> grant) => _applyGrant(grant);

  /// Reset to free tier (for testing / logout).
  void reset() {
    _tier = InkPalTier.free;
    _features = InkPalTier.free.features;
    _grantExpiry = null;
    _validated = false;
  }
}
