import 'dart:async';

import 'package:flutter/foundation.dart';

import 'recorded_action.dart';

/// Records AI and user interactions into replayable flows.
///
/// Start a recording session, perform actions (they get auto-recorded
/// via the bridge command hooks), stop, and then:
/// - Export as JSON for replay
/// - Export as Flutter integration test code
/// - Replay the flow on the same or different device
class InteractionRecorder {
  static const _maxActions = 10000;
  final List<RecordedAction> _actions = [];
  int _nextId = 0;
  bool _recording = false;
  String? _sessionName;
  String? _startRoute;
  DateTime? _startTime;

  /// Current route provider (injected from bridge).
  String? Function()? routeProvider;

  /// Screen element count provider (injected from bridge).
  int Function()? elementCountProvider;

  /// Stream of recorded actions for live subscribers.
  Stream<RecordedAction> get onAction => _actionController.stream;
  final _actionController = StreamController<RecordedAction>.broadcast();

  /// Whether currently recording.
  bool get isRecording => _recording;

  /// Name of the current recording session.
  String? get sessionName => _sessionName;

  /// All recorded actions in the current/last session.
  List<RecordedAction> get actions => List.unmodifiable(_actions);

  /// Start recording interactions.
  Map<String, dynamic> start({String? name}) {
    if (_recording) {
      return {'success': false, 'error': 'Already recording. Stop first.'};
    }
    _actions.clear();
    _nextId = 0;
    _recording = true;
    _sessionName = name ?? 'recording_${DateTime.now().millisecondsSinceEpoch}';
    _startRoute = routeProvider?.call();
    _startTime = DateTime.now();
    return {
      'success': true,
      'session': _sessionName,
      'startRoute': _startRoute,
    };
  }

  /// Stop recording and return the session summary.
  Map<String, dynamic> stop() {
    if (!_recording) {
      return {'success': false, 'error': 'Not recording.'};
    }
    _recording = false;
    return {
      'success': true,
      'session': _sessionName,
      'actionCount': _actions.length,
      'startRoute': _startRoute,
      'endRoute': routeProvider?.call(),
      'durationMs': _startTime != null
          ? DateTime.now().difference(_startTime!).inMilliseconds
          : null,
    };
  }

  /// Record an action. Called automatically by bridge command hooks.
  void record({
    required String type,
    String? label,
    Map<String, dynamic> params = const {},
    bool success = true,
  }) {
    if (!_recording) return;

    final action = RecordedAction(
      id: _nextId++,
      type: type,
      label: label,
      params: params,
      route: routeProvider?.call(),
      timestamp: DateTime.now().toIso8601String(),
      success: success,
      elementCountAfter: elementCountProvider?.call() ?? 0,
    );

    _actions.add(action);
    if (_actions.length > _maxActions) {
      _actions.removeRange(0, _actions.length - _maxActions);
      debugPrint('[InkPal] InteractionRecorder: trimmed to $_maxActions actions');
    }
    _actionController.add(action);
  }

  /// Export the recording as JSON.
  Map<String, dynamic> toJson() => {
        'session': _sessionName,
        'startRoute': _startRoute,
        'startTime': _startTime?.toIso8601String(),
        'actionCount': _actions.length,
        'actions': _actions.map((a) => a.toJson()).toList(),
      };

  /// Generate a Flutter integration test from the recording.
  String toIntegrationTest() {
    final buf = StringBuffer();
    buf.writeln("// Auto-generated by InkPal InteractionRecorder");
    buf.writeln("// Session: $_sessionName");
    buf.writeln("// Actions: ${_actions.length}");
    buf.writeln();
    buf.writeln("import 'package:flutter_test/flutter_test.dart';");
    buf.writeln("import 'package:integration_test/integration_test.dart';");
    buf.writeln();
    buf.writeln("import 'package:your_app/main.dart' as app;");
    buf.writeln();
    buf.writeln("void main() {");
    buf.writeln("  IntegrationTestWidgetsFlutterBinding.ensureInitialized();");
    buf.writeln();
    buf.writeln("  testWidgets('$_sessionName', (tester) async {");
    buf.writeln("    app.main();");
    buf.writeln("    await tester.pumpAndSettle();");
    buf.writeln();

    for (final action in _actions) {
      buf.writeln("    ${action.toTestStep()}");
      buf.writeln("    await tester.pumpAndSettle();");
      buf.writeln();
    }

    buf.writeln("  });");
    buf.writeln("}");
    return buf.toString();
  }

  /// Clear all recorded actions without stopping.
  void clear() {
    _actions.clear();
    _nextId = 0;
  }

  void dispose() {
    _actionController.close();
  }
}
